version: 2.1

jobs:
  build:
    shell: /bin/sh -leo pipefail
    environment:
      - BASH_ENV: /etc/profile

    docker:
      - image: alpine:latest
    steps:    
      - run:
          name: install curl
          command: apk add curl py-pip git bash  wget
#       - run:
#           name: install which
#           command: apk add which  
          
      - run: |
          ls -al /usr/bin/c*
          ls -ald /usr/bin
          whoami
      
      - run:
          command: |
            ls -al /usr/bin/wh*

workflows:
  whatos:
    jobs:
      - build
