version: 2.1

jobs:
  job-1:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo "This is job 1"

  job-2:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo "This is job 2"
                   sleep 20
                   
  job-3:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo "This is job 3"
                   
                   
                   
workflows:

  whodidthis:
    jobs:
      - job-1
      - job-2:
          requires:
            - job-1
            
      - request-deploy:
          type: approval
          
      - job-3:
          requires:
            - job-2
            - request-deploy
          context: daily-deployments
