version: 2.1
orbs:
  azure-cli: circleci/azure-cli@1.2.0
jobs:
  test-azure-cli-install:
    docker:
      - image: circleci/node
    steps:
      - azure-cli/install

workflows:                
  clitest:
    jobs:
      - test-azure-cli-install
  
