version: 2.1

jobs:
  build:
    shell: /bin/sh -leo pipefail
    environment:
      - BASH_ENV: /etc/profile

    docker:
      - image: alpine:latest
    steps:
      - run: echo $PATH
    
      - run:
          name: install curl
          command: apk add curl py-pip git bash  wget
      - run:
          name: install which
          command: apk add which  
          
      - run: echo $PATH
      
      - run:
          command: |
            which curl

workflows:
  whatos:
    jobs:
      - build
