version: 2.1

jobs:
  run-endpoint-ondemand-test:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo $CIRCLE_PROJECT_USERNAME

  run-endpoint-test:
    docker:
      - image: circleci/node
    steps:
      - run:
          command: |
                   echo "run-endpoint-test
                   
workflows:
#  on_demand:
#    jobs:
#      - run-endpoint-ondemand-test:
#          type: approval
#          filters:
#            branches:
#              only:
#                - master
                
  endpointTest:
    jobs:
      - run-endpoint-ondemand-test
  
