version: 2.1
orbs:
  os-detect: circleci/os-detect@0.3.0
jobs:
  detect-os:
    docker:
      - image: circleci/node
    steps:
      - os-detect/init
          
      - run: |
          echo $OSD_FAMILY
          echo $OSD_ID
          echo $OSD_VERSION

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - detect-os
