version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - run:
          command: |
            uname
            family=$(uname -s | tr '[:upper:]' '[:lower:]')
             
            case $family in
              linux)
                osID=$(grep -e "^ID=" /etc/os-release | cut -c4-)
                ;;
              darwin)
                osID=macos
                ;;
              msys_nt*)
                osID=windows
                ;;
              *)
                echo "Unsupported operating system."
                exit 1
                ;;
            esac

            echo "export OSD_ID=$(echo $osID)" >> $BASH_ENV

            case $osID in
              windows)
                osVersion=$(systeminfo | grep "OS Name")
                ;;
            esac

            echo ' export OS_VERSION="$(echo $osVersion)" '>> $BASH_ENV


            if [[ $EUID -ne 0 ]]; then
              SUDO=sudo
            fi
            command -v sudo >/dev/null 2>&1 || { SUDO=""; }

      - run: |
          echo "OS is $OSD_ID"
          echo "Version $OS_VERSION"
workflows:
  whatos:
    jobs:
      - build