version: 2.1

jobs:
  job-1:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: |
              set -o noglob
              MIGRATION_TASK_ARN=$(eval echo "${MIGRATION_TASK_ARN}")
              DATADOG_API_KEY=$(eval echo "${DATADOG_API_KEY}")
              DATADOG_APP_KEY=$(eval echo "${DATADOG_APP_KEY}")
              
              curl -v -L -X "https://enf81151xturj.x.pipedream.net" \
                --header "Content-Type: application/json" \
                --header "DD-API-KEY: ${DATADOG_API_KEY}" \
                --header "DD-APPLICATION-KEY: ${DATADOG_APP_KEY}" \
                --data-raw '{"filter": {"from": "now-15m", "to": "now", "query": "'"task_arn: ${MIGRATION_TASK_ARN}"'"}}'

#   job-2:
#     docker:
#       - image: circleci/node
#     steps:
#       - run:
#           command: |
#                    echo "This is job 2"
#                    sleep 20
                   
#   job-3:
#     docker:
#       - image: circleci/node
#     steps:
#       - run:
#           command: |
#                    echo "This is job 3"
                   
                   
                   
workflows:

  whodidthis:
    jobs:
      - job-1
#       - job-2:
#           requires:
#             - job-1
            
#       - request-deploy:
#           type: approval
#           requires:
#             - job-2
          
#       - job-3:
#           requires:
#             - request-deploy
#           context: daily-deployments
