version: 2.1

jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
    
      - run:
          name: install curl
          command: apk add curl py-pip git bash  wget
#       - run:
#           name: install which
#           command: apk add which  
      - run:
          command: |
            which ls

workflows:
  whatos:
    jobs:
      - build
