version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  
jobs:
  lecli:
    docker:
      - image:  circleci/node:12
    steps:
      - aws-cli/install:
          version: "2"
          

                   
workflows:
#  on_demand:
#    jobs:
#      - run-endpoint-ondemand-test:
#          type: approval
#          filters:
#            branches:
#              only:
#                - master
                
  endpointTest:
    jobs:
      - lecli
  
