version: 2.1

jobs:
  build-gradle:
    machine:
      image: ubuntu-1604:201903-01
      
    steps:
      - checkout
      - run: ./gradlew --version
                   
workflows:

  zebuild:
    jobs:
      - build-gradle
  
