version: 2.1

jobs:
  variable:
    parameters:
      WKSPVAR:
        type: env_var_name
        default: WORKSPACE_MOUNT_PATH
    docker:
      - image: circleci/node
    steps:
      - run:
          name: Setting workspace path variable
          command: |
              mkdir /tmp/log
              echo 'export WORKSPACE_MOUNT_PATH="/tmp"' >> BASH_ENV
              echo ${<< parameters.WKSPVAR >>}
      
          
      - persist_to_workspace:
          root: /${<< parameters.WKSPVAR >>}
          paths:
            - log
            
      - attach_workspace:
          at: ${<< parameters.WKSPVAR >>}

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - variable
