version: 2.1

jobs:
  variable:
    parameters:
      WKSPVAR:
        type: env_var_name
        default: WORKSPACE_MOUNT_PATH
    docker:
      - image: circleci/node
    steps:
      - run:
          name: Setting workspace path variable
          command: |
              echo "export WORKSPACE_MOUNT_PATH=/tmp" >> BASH_ENV
#       - attach_workspace:
#           at: ${<< parameters.WKSPVAR >>}
          
      - persist_to_workspace:
          root: ${<< parameters.WKSPVAR >>}
          paths:
            - foo/bar
            - baz

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - variable
